'use server';

import { NextResponse } from 'next/server';
import axios from 'axios';
import { collection, query, where, getDocs, deleteDoc, addDoc, serverTimestamp } from 'firebase/firestore';
import { getSdks } from '@/firebase';
import { initializeApp, getApps } from 'firebase/app';
import { firebaseConfig } from '@/firebase/config';

// Ensure Firebase is initialized
if (!getApps().length) {
  initializeApp(firebaseConfig);
}
const { firestore } = getSdks();

export async function GET(req: Request) {
  const { searchParams, origin } = new URL(req.url);
  const code = searchParams.get('code');
  const realmId = searchParams.get('realmId');
  const returnedState = searchParams.get('state');
  
  const errorUrl = new URL('/clients', origin);

  try {
    if (!returnedState) {
      throw new Error('State parameter is missing from the QuickBooks redirect.');
    }
    
    if (!code || !realmId) {
      throw new Error('Incomplete data from QuickBooks. Missing code or realmId.');
    }

    const q = query(collection(firestore, 'oauth_states'), where('state', '==', returnedState));
    const querySnapshot = await getDocs(q);

    if (querySnapshot.empty) {
      throw new Error('Invalid or expired state parameter. Please try connecting again.');
    }

    const stateDoc = querySnapshot.docs[0];
    const { clientId } = stateDoc.data();
    await deleteDoc(stateDoc.ref);

    if (!clientId) {
      throw new Error('Client ID not found in state document. Cannot connect QuickBooks account.');
    }

    const tokenResponse = await axios.post(
      'https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer',
      new URLSearchParams({
        grant_type: 'authorization_code',
        code,
        redirect_uri: process.env.NEXT_PUBLIC_QB_REDIRECT_URI!,
      }),
      {
        headers: {
          Authorization: 'Basic ' + Buffer.from(`${process.env.NEXT_PUBLIC_QB_CLIENT_ID}:${process.env.NEXT_PUBLIC_QB_CLIENT_SECRET}`).toString('base64'),
          'Content-Type': 'application/x-www-form-urlencoded',
        },
      }
    );

    const { access_token, refresh_token, expires_in, x_refresh_token_expires_in, scope } = tokenResponse.data;
    
    if (!access_token || !refresh_token) {
        throw new Error("Token exchange failed. Did not receive access_token or refresh_token.");
    }
    
    const integrationRef = collection(firestore, 'clients', clientId, 'quickBooksIntegration');
    
    // Create a new integration document. The ID will be auto-generated by Firestore.
    const newIntegrationDoc = await addDoc(integrationRef, {
      clientId: clientId,
      accessToken: access_token,
      refreshToken: refresh_token,
      realmId: realmId,
      accessTokenExpiresAt: new Date(Date.now() + expires_in * 1000),
      refreshTokenExpiresAt: new Date(Date.now() + x_refresh_token_expires_in * 1000),
      scope: scope,
      connectedAt: serverTimestamp(),
      updatedAt: serverTimestamp()
    });

    // The 'id' field of the entity should match the document ID.
    // NOTE: This is a second write, but it's necessary to ensure data integrity
    // if the document ID is needed within the document itself.
    // In our rules and logic, we refer to the doc ID, so this isn't strictly needed for now.
    // await updateDoc(newIntegrationDoc, { id: newIntegrationDoc.id });
    
    const successUrl = new URL('/clients', origin);
    successUrl.searchParams.set('success', 'true');
    return NextResponse.redirect(successUrl);

  } catch (error: any) {
    console.error('❌ QUICKBOOKS CALLBACK ERROR:', error.response?.data || error.message);
    errorUrl.searchParams.set('error', 'callback_failed');
    
    let details = 'An internal server error occurred.';
    if (axios.isAxiosError(error) && error.response?.data) {
        details = `API Error: ${JSON.stringify(error.response.data)}`;
    } else if (error instanceof Error) {
        details = error.message;
    }
    
    errorUrl.searchParams.set('details', details);
    return NextResponse.redirect(errorUrl);
  }
}
